---
# tasks file for create_vm
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "{{ ip_server }}"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "Pa$$w0rd"
    datacenter_name: "Datacenter"
    cluster_name: "Cluster"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: lab
      template: template-ubuntu-18.04
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "iscsi-datastore01"
      hardware:
        memory_mb: {{ mem_mb }}
        num_cpus: {{ number_cpus }}
      networks:
      - name: Lab
        ip: {{ ip_host }}
        netmask: {{ mask_host }}
        gateway: {{ gw_host }}
        type: static
        dns_servers: {{ dns_host }}
      customization:
        hostname: "{{ host_name }}"
        dns_servers:
        - {{ dns_1 }}
        - {{ dns_2 }}
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
